name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: project-1-changed
        with:
          filters: |
            src:
              - 'project1/**'
      - uses: dorny/paths-filter@v2
        id: project-2-changed
        with:
          filters: |
            src:
              - 'project2/**'

      # run only if some file in 'src' folder was changed
      - if: steps.project-1-changed.outputs.src == 'true'
        run: |
            
            curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                https://api.github.com/repos/arm2148/testing/dispatches \
                -d '{"event_type":"asdf_fdsa","client_payload":{"passed":false,"integration":true,"message":"This is a message"}}'
      - if: steps.project-2-changed.outputs.src == 'true'
        run: echo "Project 2 changed"

