name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: curl step
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          https://api.github.com/repos/arm2148/testing/dispatches \
          -d '{"event_type":"asdf_fdsa","client_payload":{"passed":false,"integration":true,"message":"This is a message"}}'

